# Generated by Django 6.0.3 on 2026-04-23 23:03

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0002_alter_livro_autor_alter_livro_editora_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='copias', variations={}, verbose_name='Foto')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='livros.livro', verbose_name='Livros')),
            ],
            options={
                'verbose_name': 'Cópia',
                'verbose_name_plural': 'Cópias',
            },
        ),
    ]
