# Generated by Django 6.0.5 on 2026-06-02 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Copia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isbn', models.CharField(max_length=13, unique=True, verbose_name='ISBN')),
                ('ano', models.CharField(max_length=4, verbose_name='Ano')),
                ('status', models.CharField(choices=[('D', 'Disponível'), ('E', 'Emprestado'), ('R', 'Reservado')], default='D', max_length=70, verbose_name='Status')),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='livros.livro', verbose_name='Livros')),
            ],
            options={
                'verbose_name': 'Cópia',
                'verbose_name_plural': 'Cópias',
                'ordering': ['livro__titulo'],
            },
        ),
    ]
