# Generated by Django 6.0.5 on 2026-06-05 18:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0001_initial'),
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copia',
            name='livro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='livro', to='livros.livro', verbose_name='Livro'),
        ),
    ]
