# Generated by Django 6.0.5 on 2026-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copia',
            name='status',
            field=models.CharField(choices=[('D', 'Disponível'), ('E', 'Emprestado'), ('R', 'Reservado')], default='D', max_length=70, verbose_name='Status'),
        ),
    ]
