# Generated by Django 6.0.5 on 2026-05-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0002_alter_copia_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='copia',
            options={'ordering': ['livro__titulo'], 'verbose_name': 'Cópia', 'verbose_name_plural': 'Cópias'},
        ),
        migrations.AddField(
            model_name='copia',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
