# Generated by Django 6.0.5 on 2026-05-27 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0003_alter_copia_options_copia_destaque'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copia',
            name='destaque',
        ),
    ]
