# Generated by Django 6.0.5 on 2026-06-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='secretario',
            name='senha',
        ),
    ]
