# Generated by Django 6.0.3 on 2026-05-08 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('secretarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='secretario',
            options={'ordering': ['nome'], 'verbose_name': 'Secretário', 'verbose_name_plural': 'Secretários'},
        ),
    ]
