# Generated by Django 6.0.3 on 2026-03-31 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título do livro', max_length=70, verbose_name='Título')),
                ('genero', models.CharField(help_text='Gênero do livro', max_length=70, verbose_name='Gênero')),
                ('autor', models.CharField(help_text='Autor do livro', max_length=70, verbose_name='Autor')),
                ('editora', models.CharField(help_text='Editora do livro', max_length=70, verbose_name='Editora')),
                ('status', models.CharField(help_text='Status do livro', max_length=70, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
            },
        ),
    ]
