# Generated by Django 6.0.5 on 2026-06-11 23:40

import django.db.models.deletion
import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('colecoes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='livros', variations={}, verbose_name='Foto')),
                ('titulo', models.CharField(max_length=70, verbose_name='Título')),
                ('genero', models.CharField(choices=[('Aventura', 'Aventura'), ('Biografia', 'Biografia'), ('Conto', 'Conto'), ('Drama', 'Drama'), ('Fantasia', 'Fantasia'), ('Ficção Científica', 'Ficção Científica'), ('História', 'História'), ('Poesia', 'Poesia'), ('Romance', 'Romance'), ('Suspense', 'Suspense / Terror'), ('Outros', 'Outros')], default='Outros', max_length=70, verbose_name='Gênero')),
                ('autor', models.CharField(max_length=70, verbose_name='Autor')),
                ('editora', models.CharField(max_length=70, verbose_name='Editora')),
                ('destaque', models.BooleanField(default=False)),
                ('colecao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='livros', to='colecoes.colecao', verbose_name='Coleção')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
