# Generated by Django 6.0.3 on 2026-05-12 22:21

import stdimage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', stdimage.models.StdImageField(blank=True, force_min_size=False, null=True, upload_to='livros', variations={}, verbose_name='Foto')),
                ('titulo', models.CharField(max_length=70, verbose_name='Título')),
                ('genero', models.CharField(max_length=70, verbose_name='Gênero')),
                ('autor', models.CharField(max_length=70, verbose_name='Autor')),
                ('editora', models.CharField(max_length=70, verbose_name='Editora')),
            ],
            options={
                'verbose_name': 'Livro',
                'verbose_name_plural': 'Livros',
                'ordering': ['titulo'],
            },
        ),
    ]
