# Generated by Django 6.0.5 on 2026-06-16 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(blank=True, max_length=70, null=True, verbose_name='Editora'),
        ),
    ]
