# Generated by Django 6.0.3 on 2026-04-15 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='autor',
            field=models.CharField(max_length=70, verbose_name='Autor'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=70, verbose_name='Editora'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(max_length=70, verbose_name='Gênero'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='status',
            field=models.CharField(max_length=70, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='livro',
            name='titulo',
            field=models.CharField(max_length=70, verbose_name='Título'),
        ),
    ]
