# Generated by Django 6.0.5 on 2026-05-27 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='livro',
            name='destaque',
            field=models.BooleanField(default=False),
        ),
    ]
