# Generated by Django 6.0.5 on 2026-05-28 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_livro_destaque'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='genero',
            field=models.CharField(choices=[('Aventura', 'Aventura'), ('Biografia', 'Biografia'), ('Conto', 'Conto'), ('Drama', 'Drama'), ('Fantasia', 'Fantasia'), ('Ficção Científica', 'Ficção Científica'), ('História', 'História'), ('Poesia', 'Poesia'), ('Romance', 'Romance'), ('Suspense', 'Suspense / Terror'), ('Outros', 'Outros')], default='Outros', max_length=70, verbose_name='Gênero'),
        ),
    ]
