# Generated by Django 6.0.4 on 2026-06-20 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livros', '0002_alter_livro_editora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livro',
            name='editora',
            field=models.CharField(max_length=70, verbose_name='Editora'),
        ),
    ]
