# Generated by Django 6.0.5 on 2026-05-31 00:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('colecoes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='dono',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente', verbose_name='Dono atual'),
        ),
        migrations.AddField(
            model_name='colecao',
            name='fim_exclusividade',
            field=models.DateField(blank=True, null=True, verbose_name='Fim da exclusividade'),
        ),
    ]
