# Generated by Django 6.0.3 on 2026-05-12 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('copias', '0001_initial'),
        ('secretarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopiasEmprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('copia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='copias_emprestimo_copia', to='copias.copia', verbose_name='Cópia')),
            ],
            options={
                'verbose_name': 'Cópia retirada',
                'verbose_name_plural': 'Cópias retiradas',
            },
        ),
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Clientes')),
                ('copias', models.ManyToManyField(related_name='emprestimo_copias', through='emprestimos.CopiasEmprestimo', to='copias.copia')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretarios.secretario', verbose_name='Secretários')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['data_retirada'],
            },
        ),
        migrations.AddField(
            model_name='copiasemprestimo',
            name='emprestimo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copias_emprestimo_emprestimo', to='emprestimos.emprestimo', verbose_name='Empréstimo'),
        ),
    ]
