# Generated by Django 6.0.5 on 2026-05-20 11:38

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('copias', '0001_initial'),
        ('secretarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_retirada', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('data_prevista', models.DateField(blank=True, null=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Clientes')),
                ('copias', models.ManyToManyField(to='copias.copia')),
                ('secretario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='secretarios.secretario', verbose_name='Secretários')),
            ],
            options={
                'verbose_name': 'Empréstimo',
                'verbose_name_plural': 'Empréstimos',
                'ordering': ['data_retirada'],
            },
        ),
    ]
