# Generated by Django 6.0.3 on 2026-05-15 00:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateTimeField(verbose_name=datetime.datetime(2026, 5, 15, 0, 12, 4, 573327, tzinfo=datetime.timezone.utc)),
        ),
    ]
