# Generated by Django 6.0.3 on 2026-04-30 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copiasemprestimo',
            name='data_devolucao',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='copiasemprestimo',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
