# Generated by Django 6.0.5 on 2026-06-05 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_retirada'], 'permissions': (('devolucao_emprestimo', 'Permite fazer a devolução de um empréstimo'),), 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
    ]
