# Generated by Django 6.0.5 on 2026-05-22 14:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('emprestimos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['-data_retirada'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Usuários'),
        ),
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
