# Generated by Django 6.0.3 on 2026-04-30 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_copiasemprestimo_data_devolucao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copiasemprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
