# Generated by Django 6.0.3 on 2026-05-15 00:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0002_alter_emprestimo_data_retirada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimo',
            name='data_retirada',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
