# Generated by Django 6.0.3 on 2026-05-15 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0003_alter_emprestimo_data_retirada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='copiasemprestimo',
            name='data_devolucao',
        ),
        migrations.RemoveField(
            model_name='copiasemprestimo',
            name='data_prevista',
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emprestimo',
            name='data_prevista',
            field=models.DateField(blank=True, null=True),
        ),
    ]
