# Generated by Django 6.0.3 on 2026-05-08 00:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emprestimos', '0005_alter_emprestimo_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimo',
            options={'ordering': ['data_retirada'], 'verbose_name': 'Empréstimo', 'verbose_name_plural': 'Empréstimos'},
        ),
    ]
