# Generated by Django 6.0.5 on 2026-05-20 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('copias', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_prevista_reserva', models.DateTimeField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clientes.cliente', verbose_name='Clientes')),
                ('copia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='copias.copia', verbose_name='Cópias')),
            ],
            options={
                'verbose_name': 'Reserva',
                'verbose_name_plural': 'Reservas',
                'ordering': ['data_prevista_reserva'],
            },
        ),
    ]
