# Generated by Django 6.0.3 on 2026-05-14 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='data_prevista_reserva',
            field=models.DateTimeField(),
        ),
    ]
