# Generated by Django 6.0.5 on 2026-05-22 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='data_retirada',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
