# Generated by Django 6.0.3 on 2026-05-01 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0001_initial'),
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='copia',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='copias.copia', verbose_name='Cópias'),
            preserve_default=False,
        ),
    ]
