# Generated by Django 6.0.5 on 2026-06-08 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_alter_reserva_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['data_prevista_reserva'], 'permissions': (('retirada_reserva', 'Permite fazer a retirada de uma reserva'),), 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
