# Generated by Django 6.0.3 on 2026-05-08 00:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_copia'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reserva',
            options={'ordering': ['-data_prevista_reserva'], 'verbose_name': 'Reserva', 'verbose_name_plural': 'Reservas'},
        ),
    ]
