# Generated by Django 6.0.5 on 2026-05-27 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('copias', '0002_alter_copia_status'),
        ('reservas', '0004_alter_reserva_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='copia',
        ),
        migrations.AddField(
            model_name='reserva',
            name='copias',
            field=models.ManyToManyField(to='copias.copia'),
        ),
    ]
